"""
medic.py — Medic subagent for Sentinel Swarm.

Given a failing test and the broken source, asks Bob to:
  1. Identify the exact bug causing the failure.
  2. Return the FULL corrected contents of app.py wrapped in a single
     ```python code block — nothing else.

The Medic then:
  - Backs up the original app.py to app.py.bak (preserving planted bugs)
  - Overwrites app.py with the fixed version
  - Re-runs the exact same test to confirm the fix (fix_confirmed)
  - On failure to confirm, restores the backup so the app is never left broken
"""

import os
import textwrap

from bob_client import call_bob, extract_code_block, read_source_files, run_pytest


TARGET_FILES = ["app.py"]

_PROMPT = textwrap.dedent("""\
    You are a senior software engineer performing a bug fix.

    ## Failing test
    ```python
    {test_code}
    ```

    ## pytest output (the failure)
    ```
    {pytest_output}
    ```

    ## Current source: app.py
    {file_contents}

    ## Instructions
    1. Identify the exact bug in app.py that causes the test to fail.
    2. Fix only that bug — do not refactor, rename, or change any other code.
    3. Return the complete corrected contents of app.py.

    ## Output rules — follow exactly
    - Respond with a SINGLE markdown Python code block and nothing else.
    - The block must start with ```python on its own line.
    - The block must end with ``` on its own line.
    - The block must contain the ENTIRE file — every line, including unchanged ones.
    - Zero prose, zero explanation before or after the code block.
""")


def run_medic(test_code: str, pytest_output: str, repo_path: str) -> dict:
    """
    Ask Bob to fix the bug that the Saboteur's test exposed, apply the fix,
    re-run the test, and return the results.

    Parameters
    ----------
    test_code     : the pytest test code that was generated by Saboteur
    pytest_output : the failure output from the first pytest run
    repo_path     : absolute path to the scenario directory being fixed

    Returns a dict with keys:
      fixed_source    — the corrected app.py content Bob produced
      fix_confirmed   — True if the test passes after the patch
      rerun_output    — pytest output from the confirmation run
      backup_path     — path to the app.py.bak file (original with bugs)
    """
    file_contents = read_source_files(repo_path, TARGET_FILES)
    if not file_contents:
        raise RuntimeError(f"No readable source files found in {repo_path!r}")

    prompt = _PROMPT.format(
        test_code=test_code,
        pytest_output=pytest_output,
        file_contents=file_contents,
    )

    raw_response = call_bob(prompt, workspace=repo_path, timeout=180)
    fixed_source = extract_code_block(raw_response)

    app_path = os.path.join(repo_path, "app.py")
    backup_path = app_path + ".bak"

    # Back up the original (planted-bug) version before overwriting
    with open(app_path, "r", encoding="utf-8") as fh:
        original_source = fh.read()
    with open(backup_path, "w", encoding="utf-8") as fh:
        fh.write(original_source)

    # Apply the fix
    try:
        with open(app_path, "w", encoding="utf-8") as fh:
            fh.write(fixed_source + "\n")

        # Re-run the same test against the patched code
        test_path = os.path.join(repo_path, "test_generated.py")
        rerun = run_pytest(test_path, repo_path)
    except BaseException:
        # Restore before re-raising: never leave the repo holding a
        # half-written or unverified patch (covers Ctrl-C and kill too).
        with open(app_path, "w", encoding="utf-8") as fh:
            fh.write(original_source)
        raise

    # If the fix didn't work, restore the original so the app isn't left broken
    if not rerun["passed"]:
        with open(app_path, "w", encoding="utf-8") as fh:
            fh.write(original_source)

    return {
        "fixed_source": fixed_source,
        "fix_confirmed": rerun["passed"],
        "rerun_output": rerun["output"],
        "backup_path": backup_path,
    }
